# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="gardei"
#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
#TODO: zsh autosuggestions
  git
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
function cd_with_dir {
	## dir doesn't exist on FreeBSD
	# cd $1 && dir -UA | head -10
	cd $1 && ls -UAFG | head -10
}

function tma {
	tmux attach -t $1
}

function tmd {
	tmux detach
}

alias gdh="cd_with_dir ~"
alias gdg="cd_with_dir ~/Git"
alias gdd="cd_with_dir ~/Git/Dotfiles/darwin"
alias gdh="cd_with_dir ~/Hacking"
alias gdc="cd_with_dir ~/Hacking/Compilers"
alias gdt="cd_with_dir ~/TLDR"
alias gdr="cd_with_dir ~/Research"
alias gdrc="cd_with_dir ~/Research/Current"
alias gdre="cd_with_dir ~/Research/Experiments"
alias gdalp="cd_with_dir ~/Git/ALP"
alias gdos="cd_with_dir ~/Git/os/osdev"
alias gdnfv="cd_with_dir ~/Git/nfv-benchmark"
alias la="ls -A"
alias vimrc="vim ~/.vimrc"
alias bashrc="vim ~/.bashrc"
alias zshrc="vim ~/.zshrc"
alias fishrc="vim ~/.config/fish/config.fish"
alias tmuxrc="vim ~/.tmux.conf"
alias i3rc="vim ~/.i3/config"
alias TODO="cat ~/TODO"
alias TODORC="vim ~/TODO"

# Helper functions
# zsh aliases don't take arguments
function getpdf() {
	wget robots=off -A pdf "$1"
}

function gclone() {
	git clone https://www.github.com/$1
}

unalias gd
function gd() {
	cd_with_dir $1
}

# LLVM
export LD_LIBRARY_PATH="$HOME/Hacking/compilers/llvm-9.0.1-install/lib:$LD_LIBRARY_PATH"
export PATH="$HOME/Hacking/compilers/llvm-9.0.1-install/bin:$PATH"

# gcc
#export LD_LIBRARY_PATH="$HOME/Hacking/compilers/gcc-9.2.0-install/lib:$LD_LIBRARY_PATH"
#export PATH="$HOME/Hacking/compilers/gcc-9.2.0-install/bin:$PATH"

# Android
export ANDROID_NDK_ROOT="$HOME/Qualcomm/Hexagon_SDK/3.5.1/tools/android-ndk-r19c"
export PATH="$HOME/Android/android-studio/bin:$PATH"
alias astudio="studio.sh"

# Hexagon
export PATH="$HOME/bin:$PATH"
#export HEXAGON_SDK_ROOT="$HOME/Qualcomm/Hexagon_SDK/3.5.1"
alias hexstudio="$HOME/Qualcomm/Hexagon_SDK/3.5.1/Launch\ Hexagon\ IDE"

init_hex_llvm() {
	# Qualcomm
	export PATH="$HOME/Qualcomm/Hexagon_SDK/3.5.1/tools/HEXAGON_Tools/8.3.07/Tools/bin"
	export LD_LIBRARY_PATH="$HOME/Qualcomm/Hexagon_SDK/3.5.1/tools/HEXAGON_Tools/8.3.07/Tools/lib"
}

init_android_llvm() {
	# Android llvm (Qualcomm provided)
	export LD_LIBRARY_PATH="$HOME/Qualcomm/Hexagon_SDK/3.5.1/tools/android-ndk-r19c/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/lib:$LD_LIBRARY_PATH"
	export PATH="$HOME/Qualcomm/Hexagon_SDK/3.5.1/tools/android-ndk-r19c/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/bin:$PATH"
}

# Dtrace
init_dtrace() {
	local load_script="~/Git/os/freebsd/dtrace/load_dtrace.sh"
	if [ -f $load_script ]
	then
		. $load_script
		load_dtrace_ker_mods
	fi
}

dtrace() {
	sudo dtrace $@
}

init_dtrace

# Fix character issues in tmux
export LC_ALL=en_IN.UTF-8
export LANG=en_IN.UTF-8

# Prevent terminal from locking when pressing: C-s
# (unlock is via: C-q)
stty -ixon

# Caffe
export PYTHONPATH=$HOME/Qualcomm/snpe-1.35.0.698/lib/python:$PYTHONPATH
export PYTHONPATH=$HOME/caffe/build/install/python:$PYTHONPATH
export LD_LIBRARY_PATH=$HOME/caffe/build/install/lib:$LD_LIBRARY_PATH
export PATH=$HOME/caffe/build/install/bin:$PATH
export SNPE_ROOT=$HOME/Qualcomm/snpe-1.35.0.698

# cd $HOME/Qualcomm/snpe-1.35.0.698/bin; source envsetup.sh -c ~/caffe; cd ~

adjust_brightness() {
	$HOME/.brightness_adjust.sh $1
}
alias ab=adjust_brightness

# opam configuration
test -r /Users/gardei/.opam/opam-init/init.zsh && . /Users/gardei/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/gardei/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/gardei/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/gardei/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/gardei/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

