#gittok() {
#    gpg --decrypt -q $HOME/.gtok.gpg | pbcopy
#}

export EDITOR=vim
alias vimrc='vim ~/.vimrc'
alias bashrc='vim ~/.bash_profile'
alias zshrc='vim ~/.zshrc'
alias tmuxrc='vim ~/.tmux.conf'
alias gdd='cd ~/Git/Dotfiles/unix'
alias gdos='cd ~/Git/os'
alias gdg='cd ~/Git'
alias gdr='cd ~/Apple-internal/Radar'
alias gda='cd ~/Apple-internal'
alias gdh='cd ~/Hacking'
alias gdw='cd ~/Git/llvm-worktrees'
alias gds='cd /Volumes/SSD'
alias gdsa='cd /Volumes/SSD/Apple-internal'
alias tma='tmux attach'
alias tmd='tmux detach'
alias tmux="TERM=xterm-256color tmux -2" # to make some vim colorschemes work (e.g., badwolf)
alias lldblog="~/Git/lldb-build-main-no-modules/bin/lldb -o \"log enable lldb expr types -f /tmp/lldb.log\""
alias cas="xcrun cache-build-session" # prepend to 'ninja' commands to enable build caching
alias cdback="cd ~; cd -"
alias coq=". ~/coq-shell~8.18~2023.11.command"
alias pbrehex="pbpaste | python3 ~/bin/rehex.py | pbcopy"
alias commits="git shortlog -s | sort --reverse"
         
export PATH=$PATH:~/bin
export PATH=$PATH:/opt/homebrew/bin
export PATH=$PATH:/opt/homebrew/include
export PATH=$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin
export LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/homebrew/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/homebrew/lib

#export LLVM_CACHE_CAS_PATH=/Volumes/SSD/CAS-cache
export LLVM_CACHE_CAS_PATH=/Users/jonas/CAS-cache
export CLANG_CACHE_VERIFY_MCCAS=1

export PATH="$PATH:/opt/homebrew/opt/binutils/bin"

# For git clang-format
export PATH="${PATH}:/Users/jonas/Git/llvm-project/clang/tools/clang-format/"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Custom prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%b '
NEWLINE=$'\n'
setopt PROMPT_SUBST
PROMPT='%F{green}%~%f %F{blue}${vcs_info_msg_0_}%f${NEWLINE}$ '

# Key bindings
autoload -U select-word-style
select-word-style bash
bindkey "^A" vi-beginning-of-line
bindkey "^E" vi-end-of-line
bindkey "^k" kill-line
bindkey "^w" backward-kill-word
bindkey "^f" vi-forward-char
bindkey "^b" vi-backward-char
bindkey "^d" delete-char
bindkey "^y" vi-put-after
bindkey "^[f" vi-forward-word
bindkey "^[b" vi-backward-word
bindkey "^[d" kill-word

# Increase history size from the default of  10,000
HISTSIZE=1000000

setopt inc_append_history
