# Finally start X server,
# but only if there is none running already
if ! xset q &>/dev/null; then
	read -q YN\?"Do you want to launch an X-server [y/n]"
	[[ $YN == "y" || $YN == "Y" ]] && startx
fi

source ~/.zshrc
# source ~/.zlogin
